### ISSUE TITLE
error on get assistants

### ISSUE THREAD

**Issue by ju4nr3v0l** [hiddenhatpress/openai-assistants#1]
when i try to access the assistants list  // Access the assistant
        $entities = $asstservice->list();

i get this error:

"error" => array:4 [▼
    "message" => "Invalid type for 'metadata': expected a metadata object, but got an array instead."
    "type" => "invalid_request_error"
    "param" => "metadata"
    "code" => "invalid_type"

**Comment by getinstancemz** [comment]
This should be fixed in v1.0.7 -- looks like openai got more picky about empty metadata.
